<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27271" started-at="2016-11-23T00:07:16Z" finished-at="2016-11-23T00:07:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27271" started-at="2016-11-23T00:07:16Z" finished-at="2016-11-23T00:07:43Z">
      <class name="testcases.loginTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.loginTest@cb5822]" name="beforeClass" is-config="true" duration-ms="6952" started-at="2016-11-23T00:07:16Z" finished-at="2016-11-23T00:07:23Z">
        </test-method>
        <test-method status="FAIL" signature="login_01()[pri:0, instance:testcases.loginTest@cb5822]" name="login_01" duration-ms="19569" started-at="2016-11-23T00:07:23Z" finished-at="2016-11-23T00:07:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verify yahoo mailbox is navigated expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verify yahoo mailbox is navigated expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at utils.SeleniumTestBase.assertTrue(SeleniumTestBase.java:551)
	at testcases.loginTest.login_01(loginTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcases.loginTest@cb5822]" name="afterClass" is-config="true" duration-ms="695" started-at="2016-11-23T00:07:43Z" finished-at="2016-11-23T00:07:43Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
